spring.application.name=paper-service

server.port=8082

##########################################
# MySQL
##########################################

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/researchiq_paper}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Ashish123@}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##########################################
# Eureka
##########################################

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

##########################################
# Actuator
##########################################

management.endpoints.web.exposure.include=*

##########################################
# Cloudinary
##########################################

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dz7a5elyy}
cloudinary.api-key=${CLOUDINARY_API_KEY:919699317358677}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:fB73rLpj-zY1NVbm2vrskbqE1rU}

##########################################
# RabbitMQ
##########################################

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

##########################################
# Multipart
##########################################

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:20MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:20MB}