# ===============================
# Application Configuration
# ===============================
spring.application.name=api-gateway

# ===============================
# Server Configuration
# ===============================
server.port=8080

# ===============================
# Eureka Configuration
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# Gateway Discovery Configuration
# ===============================
spring.cloud.gateway.server.webmvc.discovery.locator.enabled=true
spring.cloud.gateway.server.webmvc.discovery.locator.lower-case-service-id=true