# ===========================
# Server
# ===========================
server.port=8084

# ===========================
# Application
# ===========================
spring.application.name=insight-service

# ===========================
# MongoDB
# ===========================
spring.data.mongodb.uri=${MONGO_URI}

# ===========================
# Eureka
# ===========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===========================
# Logging
# ===========================
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.com.research.insight_service=DEBUG

# ===========================
# Gemini
# ===========================
gemini.api.key=${GEMINI_API_KEY}

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true